name: Firebase App Testing (App Hosting) on new branch
on:
  check_run:
    types: [completed]
jobs:
  run_ai_tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: |
      github.event.check_run.app.name == 'Firebase App Hosting' &&
      github.event.check_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_APP_TESTING_SERVICE_ACCOUNT }}
      - name: Run tests on App Hosting
        run: curl -sL https://firebase.tools | bash && firebase experiments:enable apptesting && firebase apptesting:execute https://ecommerce-app--ecommerce-9f120.us-central1.hosted.app
